# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0003_bthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='key',
            field=models.TextField(max_length=200),
        ),
    ]
