# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0005_auto_20171115_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='value',
            new_name='val',
        ),
    ]
