# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import threading


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0002_auto_20171112_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, threading.Thread),
        ),
    ]
