# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0004_auto_20171115_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='key',
            field=models.CharField(max_length=200),
        ),
    ]
