# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0006_auto_20171116_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BThread',
        ),
    ]
